import { StyleSheet } from "react-native";
import { height, totalSize, width } from "react-native-dimension";
import { colors } from "../../constants";
export const styles= StyleSheet.create({
    model:{
        height:height(43.98),
        width:width(100),
        borderTopLeftRadius:totalSize(2),
        borderTopRightRadius:totalSize(2),
        backgroundColor:colors.appBgColor2,
      position:'absolute',
      bottom:0
    },
    linkicon:{
        flexDirection:'row',
    },
    main:{
        backgroundColor:colors.appBgColor1,
        height:height(100),
    },
    text:{
        color:colors.appTextColor3,
        fontSize:totalSize(3),
        textAlign:'center',
        fontWeight:'700'
    },
    section:{
        height:height(19.54),
        width:width(42.30),
        borderRadius:totalSize(1.55),
        borderWidth:totalSize(.2),
        borderColor:colors.borderColor4,
        alignItems:'center',
        justifyContent:'center'
    },
    bttn:{
        width:width(89.74),
        alignSelf:'center',
        height:height(5.15),
        backgroundColor:colors.appButton3,
        borderRadius:totalSize(1.55),
        alignItems:'center',
        justifyContent:'center'
    },
    img:{
        width:width(19.23),
        height:height(8.61)
    },
    icon:{
        color:colors.appTextColor3,
        fontSize:totalSize(2.2),
        fontWeight:'700'
    },
    activeOption: {
        borderColor:colors.borderColor3,
        borderWidth:totalSize(.3)
    },
    linkmodel:{
        height:height(43.24),
        width:width(100),
        borderTopLeftRadius:totalSize(2),
        borderTopRightRadius:totalSize(2),
        backgroundColor:colors.appBgColor2,
      position:'absolute',
      bottom:0
    },
    linkicon:{
        alignSelf:'center'
    },
    btntext:{
        color:colors.appTextColor2,
    fontSize:totalSize(1.77) ,
    fontWeight:'700'   
    },
    SelectSchoolmodel:{
        height:height(89.09),
        width:width(100),
        borderTopLeftRadius:totalSize(2),
        borderTopRightRadius:totalSize(2),
        backgroundColor:colors.appBgColor2,
      position:'absolute',
      bottom:0
    },
    crossicon:{
        width:width(59),
        alignSelf:'flex-end'
    }
    ,
    subject:{
        height:height(33),
        width:width(100),
        borderTopLeftRadius:totalSize(2),
        borderTopRightRadius:totalSize(2),
        backgroundColor:colors.appBgColor2,
      position:'absolute',
      bottom:0
    },
    Del:{
        height:height(37),
        width:width(100),
        borderTopLeftRadius:totalSize(2),
        borderTopRightRadius:totalSize(2),
        backgroundColor:colors.appBgColor2,
      position:'absolute',
      bottom:0
    },
    colored:{
        width:width(42.30),
        backgroundColor:colors.appButton8
    },
    bord:{
        width:width(42.30),
        backgroundColor:colors.appButton2
    },
    deletbtn:{
        flexDirection:'row',
        justifyContent:'space-between'
    }
})